<a href="https://colab.research.google.com/github/giljr/py4Colab/blob/master/EX_01/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PYTHON REVIEW

###Functions:


In [1]:
#Python Functions
def times2(var):
  return var*2


In [2]:
times2(5)

10

In [3]:
def square(num):
  '''
  THIS IS A DOCSTRING,
  CAN GO MULTIPLY LINES
  THIS FUNCTION SQUARES A NUMBER
  '''
  return num**2

In [4]:
# Hit Shift-Tab to bring up the signature and docstring of the class
output = square(2)

In [5]:
output

4

#MAP

In [6]:
seq=[1,2,3,4,5]

In [7]:
list(map(times2, seq))

[2, 4, 6, 8, 10]

#LAMBDA

In [8]:
#def times2(var):return var*2

In [9]:
# get rid of the name of the function, cuz lambda is annonimous function (read: lambda takes var and returns var*2)
lambda var:var*2

<function __main__.<lambda>>

In [10]:

# Not usual, but feasible:)
t=lambda var:var*2

In [11]:
t(5)

10

In [12]:
# Using Map function plus Lambda function (what it is build for!)
map(lambda var:var*2, seq)

In [13]:
# Casting Map to a List
list(map(lambda var:var*2, seq))

[2, 4, 6, 8, 10]

#FILTER

In [14]:
filter(lambda var:var%2==0, seq)

In [15]:
# Filters out the even number from seq list casted to a list
list(filter(lambda var:var%2==0, seq))



[2, 4]

In [16]:
seq=['soup','dog','salad','cat','greed']

In [17]:
# Filters out 's' init words using lambda expression
filter(lambda word:word[0]=='s', seq)

In [18]:
list(filter(lambda word:word[0]=='s', seq))

['soup', 'salad']

#STRING

In [19]:
s='hello my name is j3'

In [20]:
s.upper()

'HELLO MY NAME IS J3'

In [21]:
s.lower()

'hello my name is j3'

In [22]:
my_string_list=s.split()

In [23]:
my_string_list

['hello', 'my', 'name', 'is', 'j3']

In [24]:
tweet="Go Sports!#Sports"

In [25]:
tweet.split('#')

['Go Sports!', 'Sports']

In [26]:
tweet.split('#')[0]

'Go Sports!'

In [27]:
tweet.split('#')[1]

'Sports'

In [28]:
# Number of time the word 'dog' occurs in the string
def countDog(phrase):
  count=0
  for word in phrase.lower().split():
    if word=='dog':
      count+=1
  return count

In [29]:
countDog('This dog runs faster than the other dog dude!')

2

#DICTIONARY

In [30]:
d={'key1':1, 'key2':2}

In [31]:
d.keys()

dict_keys(['key1', 'key2'])

In [32]:
d.items()

dict_items([('key1', 1), ('key2', 2)])

In [33]:
d.values()

dict_values([1, 2])

#LIST

In [34]:
lst=[1,2,3]

In [35]:
item=lst.pop()

In [36]:
item

3

In [37]:
lst

[1, 2]

In [38]:
lst.append(3)

In [39]:
lst

[1, 2, 3]

#IN word

In [40]:
'x'in['x','y', 'z']

True

In [41]:
'w'in['x', 'y', 'z']

False

#TUPLE UNPACKING
Python tuples are immutable means that they can not be modified in whole program

**Packing and Unpacking a Tuple** : In Python there is a very powerful tuple assignment feature that assigns right hand side of values into left hand side. In other way it is called unpacking of a tuple of values into a variable. In packing, we put values into a new tuple while in unpacking we extract those values into a single variable.

In [42]:
x=[(1,2),(3,4),(5,6)]

In [43]:
x[0][0]

1

In [44]:
x[0][1]


2

In [45]:
for item in x:
  print(item)

(1, 2)
(3, 4)
(5, 6)


In [46]:
for (a,b) in x:
  print(a)

1
3
5


In [47]:
for a,b in x:
  print(a+1, b+1)

2 3
4 5
6 7


#NUMPY

The reason it is so important for Data Science with Python is that alost all the libraries in the Python Ecosystem rely on NUMPY as one ot their main building blocks (Jose Portilla - Python For Data Sceince course)

NUMPY is also incredibly fastm as it has binding to C labraries.
###Installation: 
**conda install numpy** (Anaconda) 
or 
**pip install numpy**

#ARRAYS (Vectors & Matrices) in NUMPY  -> cast a list into numpy array

In [48]:
#Vectors
my_list=[1,2,3]

In [49]:
import numpy as np 
vec=np.array(my_list)

In [50]:
# 1 bracket mean 1-dimensional array ([])
vec

array([1, 2, 3])

In [51]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [52]:
import numpy as np

In [53]:
mat=np.array(my_mat)

In [54]:
# 2 brackets mean 2-dimensional array ([[]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#ARANGE in NUMPY

In [55]:
# All the way up to 10, but not including 10 -> return aN NUMPY ARRAY sequence of 10 digits counting from 0 to 10
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
# Third argument: step size you may want
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

#ZEROES & ONES & EYE(Identity matrix) in NUMPY

---



In [57]:
np.zeros(3)

array([0., 0., 0.])

In [58]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [59]:
np.ones(4)

array([1., 1., 1., 1.])

In [60]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [61]:
# IDENTITY MATRIX
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#LINSPACE (SPACED EVENLY) in NUMPY

In [62]:
# From 0, to 5 returning 10 digits spaced evenly
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

PLEASE **DON'T CONFUSE** linspace **WITH** arange:


**arange**: will take in the third argument as the **STEPS SIZE** (you want)

**linspace**: will take in the third argument as the **NUMBER OF POINTS**(evenly separeted)


#RANDOM NUMBER in NUMPY

In [63]:
# RAND differs from ARANGE because RAND returns random numbers and ARANGE return a sequence of them
np.random.rand(5)

array([0.08930558, 0.21911281, 0.20612461, 0.51468239, 0.11276573])

In [64]:
# n means Normal Distribution (return values around the Mean in gaussian distribution)
np.random.randn(2)

array([0.44034175, 1.1805967 ])

In [65]:
# Without the third parameter, it will return one digit from 1(included) to 100(not included)
np.random.randint(1,100)

84

In [66]:
# The third parameter specifuy the digits you want to return
np.random.randint(1,100,10)

array([25, 60, 41, 48, 76, 99, 86, 62, 74, 86])

Difference between **ARANGE** and **RANDINT**:

**ARANGE**: returns **sequence** of digits

**RANDINT**: returns **randonly** selected digits

In [67]:
arr=np.arange(25)

In [68]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [69]:
randarr=np.random.randint(0,50,10)

In [70]:
randarr

array([ 2, 11, 26, 19, 13, 37, 35, 36, 18, 24])

#RESHAPE in NUMPY

In [71]:
# Get the and numpy array and reshape it as you want; here reshaping arr(1_dimentional) as a matrix of 5x5 (2_dimentional)
reshapped_arr=arr.reshape(5,5)

In [72]:
reshapped_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#MAX & MIN in NUMPY 

In [73]:
reshapped_arr.min()

0

In [74]:
reshapped_arr.max()

24

#ATTRIBUTES SHAPE & DTYPE in NUMPY 
(there are **no Parentheses** cuz this is attributes:)


In [75]:
reshapped_arr.shape

(5, 5)

In [76]:
reshapped_arr.dtype

dtype('int64')

In [77]:
from numpy.random import randint

In [78]:
# TODO [PAGE LINK GOES HERE!]
print("Thank you for reading this page! Please favorite it, IF YOU LIKE:)")

Thank you for reading this page! Please favorite it, IF YOU LIKE:)
